version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.1

jobs:
  build:
    docker:
      - image: cimg/php:8.2-browsers
    working_directory: ~/laravel

    steps:
      - browser-tools/install-browser-tools
      - checkout

      - run:
          name: "Create environment file and generate app key"
          command: |
            mv .env.testing .env

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-depenedencies-{{checksum "composer.json" }}
            # fallback cache
            - v1-depenedencies-

      - run:
          name: "Install dependencies"
          command: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-depenedencies-{{checksum "composer.json" }}

      - run:
          name: "Generate App key"
          command: php artisan key:generate

      - run:
          name: "Install sqlite"
          command: sudo apt install php8.2-sqlite3

      - run:
          name: "Create database and run migrations"
          command: |
            touch database/database.sqlite
            php artisan migrate --env=testing

      - run:
          name: "Generate Passport encryption keys"
          command: php artisan passport:install

      # run test with phpunit
      - run:
          name: "run test"
          command: php artisan test
